### ISSUE TITLE
Gitterbot does not appear in Matrix

### ISSUE THREAD

**Issue by shyim** [matrix-org/matrix-appservice-gitter#80]
Hey,
i have followed 10 times the installation checked all logs. The user does not appear on server.

The only message i am getting is Unable to load crypto module: crypto will be disabled: Error: global.Olm is not defined

**Comment by Half-Shot** [comment]
That sounds worryingly like your logging isn't working, which is going to make this hard to debug. Ensure you have:

```yaml
logging:
    console: "debug"
```

**Comment by shyim** [comment]
Its already enabled. I have an empty debug `debug.log.2019-08-15` file

My config
```yaml
gitter_api_key: "xxxxxxxx"
matrix_homeserver: "http://127.0.0.1:8008"
matrix_user_domain: "matrix.friendsofshopware.de"
username_template: "${USER} (Gitter)"
matrix_admin_room: "!aDVRNSFUJJTircxyOh:matrix.friendsofshopware.de"

logging:
    console: "debug"
```
